#配置连接数据库的信息
spring:
  application:
    name: spring-z-boot-02-mybatis
  datasource:
    username: root
    password: 20040709qsx
    url: jdbc:mysql://localhost:3306/spring6?useUnicode=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qiye.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  file:
    #name: qiye-spring-boot.log
    path: D:\dev\Code\SpringBoot\spring-z-boot-05-thymeleaf\src\main\resources\log

